# configs/baseline/scfoundation_ddpm_mlp.yaml

model:
  diffusion:
    T:      1000
    beta_1: 1e-4
    beta_T: 0.02
    hidden_dim: 512
  decoder:
    latent_dim:   3072
    hidden_dim:   1024
    output_dim:   2000 # Your number of genes

data:
  # Path to the pre-computed embeddings file
  embedding_path: checkpoints/scfoundation/scrna_positive_embedding_01B-resolution_singlecell_cell_embedding_a5_resolution.npy
  path: data/scrna_data/scrna_positive.h5ad
  batch_size:  64
  num_workers: 4

train:
  batch_size: 64
  device:           cuda
  epoch:            100
  lr:               2e-4
  weight_decay:     1e-4
  grad_clip:        1.0
  warmup_multiplier: 10
  save_weight_dir:  checkpoints/scfoundation
  num_workers:      16

sample:
  batch_size:    64
  sampled_h5ad:  results/mlp_ddpm_mlp_scgpt_synthetic.h5ad