model:
  scgpt:
    model_name: "scGPT" 
  diffusion:
    T:      1000
    beta_1: 1e-4
    beta_T: 0.02
    hidden_dim: 512  

  decoder:
    latent_dim:   512  
    hidden_dim:   1024
    output_dim:   2000

data:
  path:        dataset/scrna_data/scrna_syn.h5ad
  batch_size:  64
  num_workers: 4
  label_key:   Condition

train:
  batch_size: 64
  device:           cuda
  epoch:            100
  lr:               2e-4
  weight_decay:     1e-4
  grad_clip:        1.0
  warmup_multiplier: 10
  save_weight_dir:  ./checkpoints/mlp_ddpm_mlp_scgpt
  num_workers:      16

sample:
  batch_size:    64
  sampled_h5ad:  samples/mlp_ddpm_mlp_scgpt_synthetic.h5ad
